<img src="finaldataframe.png" style="float: left; margin: 20px; height: 55px">

# Notebook 5- Compiling Final DataFrame

### _ Merging Seeking Alpha Analyses with Historical Stock Data_

---

    
    - `Links` from `FinalDataFrame` - to be used to build additional `webscraper` to gather `articlecontent` from `SeekingAlpha`
---


### Notebook Summary
- The method for merging historical stock data with long and short idea analyses from Seeking Alpha will be utilizing Pandas "datetime" functionality to:
     - Create weekly offsets for one year (52 offsets) that will represent holding periods
     - Using the time of article posting as our starting point (aka offset 0 = time of article posting), engineering new columns by applying offsets to "Time"
     - Performing a merge for each week, which will append the appropriate stock data to the corresponding date and ticker 
---

In [292]:
# Importing necessary libraries 

import pandas as pd
import numpy as np 
from dateutil import parser
from datetime import datetime
from datetime import timedelta

#### Importing Final Stocks DataFrame, Long Portfolio & Short Portfolio

In [293]:
stocks = pd.read_csv('final_stocks.csv')  # Exported from Notebook 3
long_portfolio = pd.read_csv('long_portfolio.csv')  # Exported from Notebook 2
short_portfolio = pd.read_csv('short_portfolio.csv') # Exported from Notebook 2

#### Final Ideas DataFrame

In [294]:
ideas = pd.concat([long_portfolio,short_portfolio])  # Combining for final ideas

---
## Let's Check It Out!
---

#### Quick look at the first few rows of each DataFrame

In [87]:
ideas.head(2)

,Authors,Link,Tickers,Time,Title,Strategy
0,Bull's Run,/article/4134659-campbell-soup-getting-ready-b...,CPB,2017-12-31 21:16:00,Campbell Soup Is Getting Ready For A Big Run,Long
1,Matthew McLaughlin,/article/4134637-now-good-time-get-oracle,ORCL,2017-12-31 14:21:00,Now Is A Good Time To Get In If You Don't Own ...,Long

In [88]:
stocks.head(2)

        Close        Date Tickers  Week
0  116.150002  2017-01-03    AAPL     1
1  116.019997  2017-01-04    AAPL     1

#### & make sure there are no missing values

In [89]:
# ideas.isnull().sum() - No missing values
# stocks.isnull().sum() - No missing values

#### & check out the datatypes we are working with

In [90]:
# ideas.dtypes
# stocks.dtypes

---
## Datatype Conversion 
_In order to properly interpret, analyze and model stock recommendations with historical stock pricing timeseries functionality, we must convert datatypes in order to merge the dataframes._



`Date` : Timestamp for each observation/date
- We will be relying heavily on Pandas DateTime for timeseries functionality 
- To do so, different holding periods need to be created with 'Date' as their starting point
- Historical stock data will be merged with these holding periods to investigate how accurate recommendations are when the dust settles 
- Creating holding periods aka `offsets` in  `weeklyincrements` 

---
### Converting columns to Pandas datetime objects
----

In [295]:
ideas['Time'] = pd.to_datetime(ideas['Time'])
stocks['Date'] = pd.to_datetime(stocks['Date'])

# Check progress

print(ideas['Time'].head(1))
print(stocks['Date'].head(1))

0   2017-12-31 21:16:00
Name: Time, dtype: datetime64[ns]
0   2017-01-03
Name: Date, dtype: datetime64[ns]

---
### Creating weekly offsets for 1 year
----
_Note : The largest increment timedelta can hold is days_

In [296]:
# Compiling list of weeks in terms of days (multiples of 7)
#
weeks = list(range(7,365,7)) 
#
# Compiling list of timedeltas for same range
offsets = list(pd.timedelta_range(start, periods=52, freq= '7D'))
#
# Iterating through both lists, adding each offset to time of article posting
for weeks_value, offsets_value in zip(weeks, offsets):
    ideas[weeks_value] = ideas['Time'] + offsets_value

In [299]:
ideas.head(5)

,Authors,Link,Tickers,Time,Title,Strategy,7,14,21,28,...,301,308,315,322,329,336,343,350,357,364
0,Bull's Run,/article/4134659-campbell-soup-getting-ready-b...,CPB,2017-12-31 21:16:00,Campbell Soup Is Getting Ready For A Big Run,Long,2018-01-07 21:16:00,2018-01-14 21:16:00,2018-01-21 21:16:00,2018-01-28 21:16:00,...,2018-10-28 21:16:00,2018-11-04 21:16:00,2018-11-11 21:16:00,2018-11-18 21:16:00,2018-11-25 21:16:00,2018-12-02 21:16:00,2018-12-09 21:16:00,2018-12-16 21:16:00,2018-12-23 21:16:00,2018-12-30 21:16:00
1,Matthew McLaughlin,/article/4134637-now-good-time-get-oracle,ORCL,2017-12-31 14:21:00,Now Is A Good Time To Get In If You Don't Own ...,Long,2018-01-07 14:21:00,2018-01-14 14:21:00,2018-01-21 14:21:00,2018-01-28 14:21:00,...,2018-10-28 14:21:00,2018-11-04 14:21:00,2018-11-11 14:21:00,2018-11-18 14:21:00,2018-11-25 14:21:00,2018-12-02 14:21:00,2018-12-09 14:21:00,2018-12-16 14:21:00,2018-12-23 14:21:00,2018-12-30 14:21:00
2,Pinxter Analytics,/article/4134641-alaska-air-set-takeoff,ALK,2017-12-31 14:17:00,Alaska Air: Set For Takeoff,Long,2018-01-07 14:17:00,2018-01-14 14:17:00,2018-01-21 14:17:00,2018-01-28 14:17:00,...,2018-10-28 14:17:00,2018-11-04 14:17:00,2018-11-11 14:17:00,2018-11-18 14:17:00,2018-11-25 14:17:00,2018-12-02 14:17:00,2018-12-09 14:17:00,2018-12-16 14:17:00,2018-12-23 14:17:00,2018-12-30 14:17:00
3,HealthBlogger,/article/4134638-went-wrong-shire-2017-2018-wi...,SHPG,2017-12-31 13:56:00,What Went Wrong For Shire In 2017 And Why 2018...,Long,2018-01-07 13:56:00,2018-01-14 13:56:00,2018-01-21 13:56:00,2018-01-28 13:56:00,...,2018-10-28 13:56:00,2018-11-04 13:56:00,2018-11-11 13:56:00,2018-11-18 13:56:00,2018-11-25 13:56:00,2018-12-02 13:56:00,2018-12-09 13:56:00,2018-12-16 13:56:00,2018-12-23 13:56:00,2018-12-30 13:56:00
4,Josh Arnold,/article/4134627-targets-biggest-risk-2018,TGT,2017-12-31 13:15:00,Target's Biggest Risk In 2018,Long,2018-01-07 13:15:00,2018-01-14 13:15:00,2018-01-21 13:15:00,2018-01-28 13:15:00,...,2018-10-28 13:15:00,2018-11-04 13:15:00,2018-11-11 13:15:00,2018-11-18 13:15:00,2018-11-25 13:15:00,2018-12-02 13:15:00,2018-12-09 13:15:00,2018-12-16 13:15:00,2018-12-23 13:15:00,2018-12-30 13:15:00

In [300]:
ideas.dtypes

Authors             object
Link                object
Tickers             object
Time        datetime64[ns]
Title               object
Strategy            object
7           datetime64[ns]
14          datetime64[ns]
21          datetime64[ns]
28          datetime64[ns]
35          datetime64[ns]
42          datetime64[ns]
49          datetime64[ns]
56          datetime64[ns]
63          datetime64[ns]
70          datetime64[ns]
77          datetime64[ns]
84          datetime64[ns]
91          datetime64[ns]
98          datetime64[ns]
105         datetime64[ns]
112         datetime64[ns]
119         datetime64[ns]
126         datetime64[ns]
133         datetime64[ns]
140         datetime64[ns]
147         datetime64[ns]
154         datetime64[ns]
161         datetime64[ns]
168         datetime64[ns]
175         datetime64[ns]
182         datetime64[ns]
189         datetime64[ns]
196         datetime64[ns]
203         datetime64[ns]
210         datetime64[ns]
217         datetime64[ns]
224         datetime64[ns]
231         datetime64[ns]
238         datetime64[ns]
245         datetime64[ns]
252         datetime64[ns]
259         datetime64[ns]
266         datetime64[ns]
273         datetime64[ns]
280         datetime64[ns]
287         datetime64[ns]
294         datetime64[ns]
301         datetime64[ns]
308         datetime64[ns]
315         datetime64[ns]
322         datetime64[ns]
329         datetime64[ns]
336         datetime64[ns]
343         datetime64[ns]
350         datetime64[ns]
357         datetime64[ns]
364         datetime64[ns]
dtype: object

### 2. Creating `offsets` aka Holding Periods off when Ideas Recommended
- The `timedelta` feature in Pandas allows for the easy adding and subtracting of datetime objects 
- Utilized to engineer weekly `offsets` for a year (52 offsets) 
- `Time` from article posting used as starting point:
                Ideas['Time'] = offset_0

    _Note:_ The largest increment `timedelta` can hold is `days`

In [285]:
weeks = list(range(7,365,7))
offsets = list(pd.timedelta_range(start, periods=52, freq= '7D'))

for weeks_value, offsets_value in zip(weeks, offsets):
    ideas[weeks_value] = ideas['Time'] + offsets_value

In [286]:
to_datetime = lambda x: pd.to_datetime(x)
to_week = lambda x: x.dt.week

In [287]:
# Drop the string variable so that applymap() can run
ideas = ideas.drop(['Authors','Link','Time','Tickers','Title','Strategy'], axis=1)

# Return the square root of every cell in the dataframe
ideas.applymap(to_datetime)

,7,14,21,28,35,42,49,56,63,70,...,301,308,315,322,329,336,343,350,357,364
0,2018-01-07 21:16:00,2018-01-14 21:16:00,2018-01-21 21:16:00,2018-01-28 21:16:00,2018-02-04 21:16:00,2018-02-11 21:16:00,2018-02-18 21:16:00,2018-02-25 21:16:00,2018-03-04 21:16:00,2018-03-11 21:16:00,...,2018-10-28 21:16:00,2018-11-04 21:16:00,2018-11-11 21:16:00,2018-11-18 21:16:00,2018-11-25 21:16:00,2018-12-02 21:16:00,2018-12-09 21:16:00,2018-12-16 21:16:00,2018-12-23 21:16:00,2018-12-30 21:16:00
1,2018-01-07 14:21:00,2018-01-14 14:21:00,2018-01-21 14:21:00,2018-01-28 14:21:00,2018-02-04 14:21:00,2018-02-11 14:21:00,2018-02-18 14:21:00,2018-02-25 14:21:00,2018-03-04 14:21:00,2018-03-11 14:21:00,...,2018-10-28 14:21:00,2018-11-04 14:21:00,2018-11-11 14:21:00,2018-11-18 14:21:00,2018-11-25 14:21:00,2018-12-02 14:21:00,2018-12-09 14:21:00,2018-12-16 14:21:00,2018-12-23 14:21:00,2018-12-30 14:21:00
2,2018-01-07 14:17:00,2018-01-14 14:17:00,2018-01-21 14:17:00,2018-01-28 14:17:00,2018-02-04 14:17:00,2018-02-11 14:17:00,2018-02-18 14:17:00,2018-02-25 14:17:00,2018-03-04 14:17:00,2018-03-11 14:17:00,...,2018-10-28 14:17:00,2018-11-04 14:17:00,2018-11-11 14:17:00,2018-11-18 14:17:00,2018-11-25 14:17:00,2018-12-02 14:17:00,2018-12-09 14:17:00,2018-12-16 14:17:00,2018-12-23 14:17:00,2018-12-30 14:17:00
3,2018-01-07 13:56:00,2018-01-14 13:56:00,2018-01-21 13:56:00,2018-01-28 13:56:00,2018-02-04 13:56:00,2018-02-11 13:56:00,2018-02-18 13:56:00,2018-02-25 13:56:00,2018-03-04 13:56:00,2018-03-11 13:56:00,...,2018-10-28 13:56:00,2018-11-04 13:56:00,2018-11-11 13:56:00,2018-11-18 13:56:00,2018-11-25 13:56:00,2018-12-02 13:56:00,2018-12-09 13:56:00,2018-12-16 13:56:00,2018-12-23 13:56:00,2018-12-30 13:56:00
4,2018-01-07 13:15:00,2018-01-14 13:15:00,2018-01-21 13:15:00,2018-01-28 13:15:00,2018-02-04 13:15:00,2018-02-11 13:15:00,2018-02-18 13:15:00,2018-02-25 13:15:00,2018-03-04 13:15:00,2018-03-11 13:15:00,...,2018-10-28 13:15:00,2018-11-04 13:15:00,2018-11-11 13:15:00,2018-11-18 13:15:00,2018-11-25 13:15:00,2018-12-02 13:15:00,2018-12-09 13:15:00,2018-12-16 13:15:00,2018-12-23 13:15:00,2018-12-30 13:15:00
5,2018-01-07 13:13:00,2018-01-14 13:13:00,2018-01-21 13:13:00,2018-01-28 13:13:00,2018-02-04 13:13:00,2018-02-11 13:13:00,2018-02-18 13:13:00,2018-02-25 13:13:00,2018-03-04 13:13:00,2018-03-11 13:13:00,...,2018-10-28 13:13:00,2018-11-04 13:13:00,2018-11-11 13:13:00,2018-11-18 13:13:00,2018-11-25 13:13:00,2018-12-02 13:13:00,2018-12-09 13:13:00,2018-12-16 13:13:00,2018-12-23 13:13:00,2018-12-30 13:13:00
6,2018-01-07 13:06:00,2018-01-14 13:06:00,2018-01-21 13:06:00,2018-01-28 13:06:00,2018-02-04 13:06:00,2018-02-11 13:06:00,2018-02-18 13:06:00,2018-02-25 13:06:00,2018-03-04 13:06:00,2018-03-11 13:06:00,...,2018-10-28 13:06:00,2018-11-04 13:06:00,2018-11-11 13:06:00,2018-11-18 13:06:00,2018-11-25 13:06:00,2018-12-02 13:06:00,2018-12-09 13:06:00,2018-12-16 13:06:00,2018-12-23 13:06:00,2018-12-30 13:06:00
7,2018-01-07 11:37:00,2018-01-14 11:37:00,2018-01-21 11:37:00,2018-01-28 11:37:00,2018-02-04 11:37:00,2018-02-11 11:37:00,2018-02-18 11:37:00,2018-02-25 11:37:00,2018-03-04 11:37:00,2018-03-11 11:37:00,...,2018-10-28 11:37:00,2018-11-04 11:37:00,2018-11-11 11:37:00,2018-11-18 11:37:00,2018-11-25 11:37:00,2018-12-02 11:37:00,2018-12-09 11:37:00,2018-12-16 11:37:00,2018-12-23 11:37:00,2018-12-30 11:37:00
8,2018-01-07 11:30:00,2018-01-14 11:30:00,2018-01-21 11:30:00,2018-01-28 11:30:00,2018-02-04 11:30:00,2018-02-11 11:30:00,2018-02-18 11:30:00,2018-02-25 11:30:00,2018-03-04 11:30:00,2018-03-11 11:30:00,...,2018-10-28 11:30:00,2018-11-04 11:30:00,2018-11-11 11:30:00,2018-11-18 11:30:00,2018-11-25 11:30:00,2018-12-02 11:30:00,2018-12-09 11:30:00,2018-12-16 11:30:00,2018-12-23 11:30:00,2018-12-30 11:30:00
9,2018-01-07 11:19:00,2018-01-14 11:19:00,2018-01-21 11:19:00,2018-01-28 11:19:00,2018-02-04 11:19:00,2018-02-11 11:19:00,2018-02-18 11:19:00,2018-02-25 11:19:00,2018-03-04 11:19:00,2018-03-11 11:19:00,...,2018-10-28 11:19:00,2018-11-04 11:19:00,2018-11-11 11:19:00,2018-11-18 11:19:00,2018-11-25 11:19:00,2018-12-02 11:19:00,2018-12-09 11:19:00,2018-12-16 11:19:00,2018-12-23 11:19:00,2018-12-30 11:19:00
10,2018-01-07 10:42:00,2018-01-14 10:42:00,2018-01-21 10:42:00,2018-01-28 10:42:00,2018-02-04 10:42:00,2018-02-11 10:42:00,2018-02-18 10:42:00,2018-02-25 10:42:00,2018-03-04 10:42:00,2018-03-11 10:42:00,...,2018-10-28 10:42:00,2018-11-04 10:42:00,2018-11-11 10:42:00,2018-11-18 10:42:00,2018-11-25 10:42:00,2018-12-02 10:42:00,2018-12-09 10:42:00,2018-12-16 10:42:00,2018-12-23 10:42:00,2018-12-30 10:42:00
11,2018-01-07 10:26:00,2018-01-14 10:26:00,2018-01-21 10:26:00,2018-01-28 10:26:00,2018-02-04 10:26:00,2018-02-11 10:26:00,2018-02-18 10:26:00,2018-02-25 10:26:00,2018-03-04 10:26:00,2018-03-11 10:26:00,...,2018-10-28 10:26:00,2018-11-04 10:26:00,2018-11-11 10:26:00,2018-11-18 10:26:00,2018-11-25 10:26:00,2018-12-02 10:26:00,2018-12-09 10:26:00,2018-12-16 10:26:00,2018-12-23 10:26:00,2018-12-30 10:26:00
12,2018-01-07 09:52:00,2018-01-14 09:52:00,2018-01-21 09:52:00,2018-01-28 09:52:00,2018-02-04 09:52:00,2018-02-11 09:52:00,2018-02-18 09:52:00,2018-02-25 09:52:00,2018-03-04 09:52:00,2018-03-11 09:52:00,...,2018-10-28 09:52:00,2018-11-04 09:52:00,2018-11-11 09:52:00,2018-11-18 09:52:00,2018-11-25 09:52:00,2018-12-02 09:52:00,2018-12-09 09:52:00,2018-12-16 09:52:00,2018-12-23 09:52:00,2018-12-30 09:52:00
13,2018-01-07 04:34:00,2018-01-14 04:34:00,2018-01-21 04:34:00,2018-01-28 04:34:00,2018-02-04 04:34:00,2018-02-11 04:34:00,2018-02-18 04:34:00,2018-02-25 04:34:00,2018-03-04 04:34:00,2018-03-11 04:34:00,...,2018-10-28 04:34:00,2018-11-04 04:34:00,2018-11-11 04:34:00,2018-11-18 04:34:00,2018-11-25 04:34:00,2018-12-02 04:34:00,2018-12-09 04:34:00,2018-12-16 04:34:00,2018-12-23 04:34:00,2018-12-30 04:34:00
14,2018-01-07 04:17:00,2018-01-14 04:17:00,2018-01-21 04:17:00,2018-01-28 04:17:00,2018-02-04 04:17:00,2018-02-11 04:17:00,2018-02-18 04:17:00,2018-02-25 04:17:00,2018-03-04 04:17:00,2018-03-11 04:17:00,...,2018-10-28 04:17:00,2018-11-04 04:17:00,2018-11-11 04:17:00,2018-11-18 04:17:00,2018-11-25 04:17:00,2018-12-02 04:17:00,2018-12-09 04:17:00,2018-12-16 04:17:00,2018-12-23 04:17:00,2018-12-30 04:17:00
15,2018-01-07 00:00:00,2018-01-14 00:00:00,2018-01-21 00:00:00,2018-01-28 00:00:00,2018-02-04 00:00:00,2018-02-11 00:00:00,2018-02-18 00:00:00,2018-02-25 00:00:00,2018-03-04 00:00:00,2018-03-11 00:00:00,...,2018-10-28 00:00:00,2018-11-04 00:00:00,2018-11-11 00:00:00,2018-11-18 00:00:00,2018-11-25 00:00:00,2018-12-02 00:00:00,2018-12-09 00:00:00,2018-12-16 00:00:00,2018-12-23 00:00:00,2018-12-30 00:00:00
16,2018-01-06 23:40:00,2018-01-13 23:40:00,2018-01-20 23:40:00,2018-01-27 23:40:00,2018-02-03 23:40:00,2018-02-10 23:40:00,2018-02-17 23:40:00,2018-02-24 23:40:00,2018-03-03 23:40:00,2018-03-10 23:40:00,...,2018-10-27 23:40:00,2018-11-03 23:40:00,2018-11-10 23:40:00,2018-11-17 23:40:00,2018-11-24 23:40:00,2018-12-01 23:40:00,2018-12-08 23:40:00,2018-12-15 23:40:00,2018-12-22 23:40:00,2018-12-29 23:40:00
17,2018-01-06 13:54:00,2018-01-13 13:54:00,2018-01-20 13:54:00,2018-01-27 13:54:00,2018-02-03 13:54:00,2018-02-10 13:54:00,2018-02-17 13:54:00,2018-02-24 13:54:00,2018-03-03 13:54:00,2018-03-10 13:54:00,...,2018-10-27 13:54:00,2018-11-03 13:54:00,2018-11-10 13:54:00,2018-11-17 13:54:00,2018-11-24 13:54:00,2018-12-01 13:54:00,2018-12-08 13:54:00,2018-12-15 13:54:00,2018-12-22 13:54:00,2018-12-29 13:54:00
18,2018-01-06 13:14:00,2018-01-13 13:14:00,2018-01-20 13:14:00,2018-01-27 13:14:00,2018-02-03 13:14:00,2018-02-10 13:14:00,2018-02-17 13:14:00,2018-02-24 13:14:00,2018-03-03 13:14:00,2018-03-10 13:14:00,...,2018-10-27 13:14:00,2018-11-03 13:14:00,2018-11-10 13:14:00,2018-11-17 13:14:00,2018-11-24 13:14:00,2018-12-01 13:14:00,2018-12-08 13:14:00,2018-12-15 13:14:00,2018-12-22 13:14:00,2018-12-29 13:14:00
19,2018-01-06 06:37:00,2018-01-13 06:37:00,2018-01-20 06:37:00,2018-01-27 06:37:00,2018-02-03 06:37:00,2018-02-10 06:37:00,2018-02-17 06:37:00,2018-02-24 06:37:00,2018-03-03 06:37:00,2018-03-10 06:37:00,...,2018-10-27 06:37:00,2018-11-03 06:37:00,2018-11-10 06:37:00,2018-11-17 06:37:00,2018-11-24 06:37:00,2018-12-01 06:37:00,2018-12-08 06:37:00,2018-12-15 06:37:00,2018-12-22 06:37:00,2018-12-29 06:37:00
20,2018-01-06 06:12:00,2018-01-13 06:12:00,2018-01-20 06:12:00,2018-01-27 06:12:00,2018-02-03 06:12:00,2018-02-10 06:12:00,2018-02-17 06:12:00,2018-02-24 06:12:00,2018-03-03 06:12:00,2018-03-10 06:12:00,...,2018-10-27 06:12:00,2018-11-03 06:12:00,2018-11-10 06:12:00,2018-11-17 06:12:00,2018-11-24 06:12:00,2018-12-01 06:12:00,2018-12-08 06:12:00,2018-12-15 06:12:00,2018-12-22 06:12:00,2018-12-29 06:12:00
21,2018-01-06 02:01:00,2018-01-13 02:01:00,2018-01-20 02:01:00,2018-01-27 02:01:00,2018-02-03 02:01:00,2018-02-10 02:01:00,2018-02-17 02:01:00,2018-02-24 02:01:00,2018-03-03 02:01:00,2018-03-10 02:01:00,...,2018-10-27 02:01:00,2018-11-03 02:01:00,2018-11-10 02:01:00,2018-11-17 02:01:00,2018-11-24 02:01:00,2018-12-01 02:01:00,2018-12-08 02:01:00,2018-12-15 02:01:00,2018-12-22 02:01:00,2018-12-29 02:01:00
22,2018-01-06 01:26:00,2018-01-13 01:26:00,2018-01-20 01:26:00,2018-01-27 01:26:00,2018-02-03 01:26:00,2018-02-10 01:26:00,2018-02-17 01:26:00,2018-02-24 01:26:00,2018-03-03 01:26:00,2018-03-10 01:26:00,...,2018-10-27 01:26:00,2018-11-03 01:26:00,2018-11-10 01:26:00,2018-11-17 01:26:00,2018-11-24 01:26:00,2018-12-01 01:26:00,2018-12-08 01:26:00,2018-12-15 01:26:00,2018-12-22 01:26:00,2018-12-29 01:26:00
23,2018-01-05 18:55:00,2018-01-12 18:55:00,2018-01-19 18:55:00,2018-01-26 18:55:00,2018-02-02 18:55:00,2018-02-09 18:55:00,2018-02-16 18:55:00,2018-02-23 18:55:00,2018-03-02 18:55:00,2018-03-09 18:55:00,...,2018-10-26 18:55:00,2018-11-02 18:55:00,2018-11-09 18:55:00,2018-11-16 18:55:00,2018-11-23 18:55:00,2018-11-30 18:55:00,2018-12-07 18:55:00,2018-12-14 18:55:00,2018-12-21 18:55:00,2018-12-28 18:55:00
24,2018-01-05 17:41:00,2018-01-12 17:41:00,2018-01-19 17:41:00,2018-01-26 17:41:00,2018-02-02 17:41:00,2018-02-09 17:41:00,2018-02-16 17:41:00,2018-02-23 17:41:00,2018-03-02 17:41:00,2018-03-09 17:41:00,...,2018-10-26 17:41:00,2018-11-02 17:41:00,2018-11-09 17:41:00,2018-11-16 17:41:00,2018-11-23 17:41:00,2018-11-30 17:41:00,2018-12-07 17:41:00,2018-12-14 17:41:00,2018-12-21 17:41:00,2018-12-28 17:41:00
25,2018-01-05 17:19:00,2018-01-12 17:19:00,2018-01-19 17:19:00,2018-01-26 17:19:00,2018-02-02 17:19:00,2018-02-09 17:19:00,2018-02-16 17:19:00,2018-02-23 17:19:00,2018-03-02 17:19:00,2018-03-09 17:19:00,...,2018-10-26 17:19:00,2018-11-02 17:19:00,2018-11-09 17:19:00,2018-11-16 17:19:00,2018-11-23 17:19:00,2018-11-30 17:19:00,2018-12-07 17:19:00,2018-12-14 17:19:00,2018-12-21 17:19:00,2018-12-28 17:19:00
26,2018-01-05 12:33:00,2018-01-12 12:33:00,2018-01-19 12:33:00,2018-01-26 12:33:00,2018-02-02 12:33:00,2018-02-09 12:33:00,2018-02-16 12:33:00,2018-02-23 12:33:00,2018-03-02 12:33:00,2018-03-09 12:33:00,...,2018-10-26 12:33:00,2018-11-02 12:33:00,2018-11-09 12:33:00,2018-11-16 12:33:00,2018-11-23 12:33:00,2018-11-30 12:33:00,2018-12-07 12:33:00,2018-12-14 12:33:00,2018-12-21 12:33:00,2018-12-28 12:33:00
27,2018-01-05 12:06:00,2018-01-12 12:06:00,2018-01-19 12:06:00,2018-01-26 12:06:00,2018-02-02 12:06:00,2018-02-09 12:06:00,2018-02-16 12:06:00,2018-02-23 12:06:00,2018-03-02 12:06:00,2018-03-09 12:06:00,...,2018-10-26 12:06:00,2018-11-02 12:06:00,2018-11-09 12:06:00,2018-11-16 12:06:00,2018-11-23 12:06:00,2018-11-30 12:06:00,2018-12-07 12:06:00,2018-12-14 12:06:00,2018-12-21 12:06:00,2018-12-28 12:06:00
28,2018-01-05 11:36:00,2018-01-12 11:36:00,2018-01-19 11:36:00,2018-01-26 11:36:00,2018-02-02 11:36:00,2018-02-09 11:36:00,2018-02-16 11:36:00,2018-02-23 11:36:00,2018-03-02 11:36:00,2018-03-09 11:36:00,...,2018-10-26 11:36:00,2018-11-02 11:36:00,2018-11-09 11:36:00,2018-11-16 11:36:00,2018-11-23 11:36:00,2018-11-30 11:36:00,2018-12-07 11:36:00,2018-12-14 11:36:00,2018-12-21 11:36:00,2018-12-28 11:36:00
29,2018-01-05 10:32:00,2018-01-12 10:32:00,2018-01-19 10:32:00,2018-01-26 10:32:00,2018-02-02 10:32:00,2018-02-09 10:32:00,2018-02-16 10:32:00,2018-02-23 10:32:00,2018-03-02 10:32:00,2018-03-09 10:32:00,...,2018-10-26 10:32:00,2018-11-02 10:32:00,2018-11-09 10:32:00,2018-11-16 10:32:00,2018-11-23 10:32:00,2018-11-30 10:32:00,2018-12-07 10:32:00,2018-12-14 10:32:00,2018-12-21 10:32:00,2018-12-28 10:32:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,2017-01-27 13:23:00,2017-02-03 13:23:00,2017-02-10 13:23:00,2017-02-17 13:23:00,2017-02-24 13:23:00,2017-03-03 13:23:00,2017-03-10 13:23:00,2017-03-17 13:23:00,2017-03-24 13:23:00,2017-03-31 13:23:00,...,2017-11-17 13:23:00,2017-11-24 13:23:00,2017-12-01 13:23:00,2017-12-08 13:23:00,2017-12-15 13:23:00,2017-12-22 13:23:00,2017-12-29 13:23:00,2018-01-05 13:23:00,2018-01-12 13:23:00,2018-01-19 13:23:00
1298,2017-01-27 12:01:00,2017-02-03 12:01:00,2017-02-10 12:01:00,2017-02-17 12:01:00,2017-02-24 12:01:00,2017-03-03 12:01:00,2017-03-10 12:01:00,2017-03-17 12:01:00,2017-03-24 12:01:00,2017-03-31 12:01:00,...,2017-11-17 12:01:00,2017-11-24 12:01:00,2017-12-01 12:01:00,2017-12-08 12:01:00,2017-12-15 12:01:00,2017-12-22 12:01:00,2017-12-29 12:01:00,2018-01-05 12:01:00,2018-01-12 12:01:00,2018-01-19 12:01:00
1299,2017-01-26 11:54:00,2017-02-02 11:54:00,2017-02-09 11:54:00,2017-02-16 11:54:00,2017-02-23 11:54:00,2017-03-02 11:54:00,2017-03-09 11:54:00,2017-03-16 11:54:00,2017-03-23 11:54:00,2017-03-30 11:54:00,...,2017-11-16 11:54:00,2017-11-23 11:54:00,2017-11-30 11:54:00,2017-12-07 11:54:00,2017-12-14 11:54:00,2017-12-21 11:54:00,2017-12-28 11:54:00,2018-01-04 11:54:00,2018-01-11 11:54:00,2018-01-18 11:54:00
1300,2017-01-26 11:52:00,2017-02-02 11:52:00,2017-02-09 11:52:00,2017-02-16 11:52:00,2017-02-23 11:52:00,2017-03-02 11:52:00,2017-03-09 11:52:00,2017-03-16 11:52:00,2017-03-23 11:52:00,2017-03-30 11:52:00,...,2017-11-16 11:52:00,2017-11-23 11:52:00,2017-11-30 11:52:00,2017-12-07 11:52:00,2017-12-14 11:52:00,2017-12-21 11:52:00,2017-12-28 11:52:00,2018-01-04 11:52:00,2018-01-11 11:52:00,2018-01-18 11:52:00
1301,2017-01-26 11:30:00,2017-02-02 11:30:00,2017-02-09 11:30:00,2017-02-16 11:30:00,2017-02-23 11:30:00,2017-03-02 11:30:00,2017-03-09 11:30:00,2017-03-16 11:30:00,2017-03-23 11:30:00,2017-03-30 11:30:00,...,2017-11-16 11:30:00,2017-11-23 11:30:00,2017-11-30 11:30:00,2017-12-07 11:30:00,2017-12-14 11:30:00,2017-12-21 11:30:00,2017-12-28 11:30:00,2018-01-04 11:30:00,2018-01-11 11:30:00,2018-01-18 11:30:00
1302,2017-01-26 10:53:00,2017-02-02 10:53:00,2017-02-09 10:53:00,2017-02-16 10:53:00,2017-02-23 10:53:00,2017-03-02 10:53:00,2017-03-09 10:53:00,2017-03-16 10:53:00,2017-03-23 10:53:00,2017-03-30 10:53:00,...,2017-11-16 10:53:00,2017-11-23 10:53:00,2017-11-30 10:53:00,2017-12-07 10:53:00,2017-12-14 10:53:00,2017-12-21 10:53:00,2017-12-28 10:53:00,2018-01-04 10:53:00,2018-01-11 10:53:00,2018-01-18 10:53:00
1303,2017-01-26 08:17:00,2017-02-02 08:17:00,2017-02-09 08:17:00,2017-02-16 08:17:00,2017-02-23 08:17:00,2017-03-02 08:17:00,2017-03-09 08:17:00,2017-03-16 08:17:00,2017-03-23 08:17:00,2017-03-30 08:17:00,...,2017-11-16 08:17:00,2017-11-23 08:17:00,2017-11-30 08:17:00,2017-12-07 08:17:00,2017-12-14 08:17:00,2017-12-21 08:17:00,2017-12-28 08:17:00,2018-01-04 08:17:00,2018-01-11 08:17:00,2018-01-18 08:17:00
1304,2017-01-25 06:27:00,2017-02-01 06:27:00,2017-02-08 06:27:00,2017-02-15 06:27:00,2017-02-22 06:27:00,2017-03-01 06:27:00,2017-03-08 06:27:00,2017-03-15 06:27:00,2017-03-22 06:27:00,2017-03-29 06:27:00,...,2017-11-15 06:27:00,2017-11-22 06:27:00,2017-11-29 06:27:00,2017-12-06 06:27:00,2017-12-13 06:27:00,2017-12-20 06:27:00,2017-12-27 06:27:00,2018-01-03 06:27:00,2018-01-10 06:27:00,2018-01-17 06:27:00
1305,2017-01-24 16:14:00,2017-01-31 16:14:00,2017-02-07 16:14:00,2017-02-14 16:14:00,2017-02-21 16:14:00,2017-02-28 16:14:00,2017-03-07 16:14:00,2017-03-14 16:14:00,2017-03-21 16:14:00,2017-03-28 16:14:00,...,2017-11-14 16:14:00,2017-11-21 16:14:00,2017-11-28 16:14:00,2017-12-05 16:14:00,2017-12-12 16:14:00,2017-12-19 16:14:00,2017-12-26 16:14:00,2018-01-02 16:14:00,2018-01-09 16:14:00,2018-01-16 16:14:00
1306,2017-01-24 14:43:00,2017-01-31 14:43:00,2017-02-07 14:43:00,2017-02-14 14:43:00,2017-02-21 14:43:00,2017-02-28 14:43:00,2017-03-07 14:43:00,2017-03-14 14:43:00,2017-03-21 14:43:00,2017-03-28 14:43:00,...,2017-11-14 14:43:00,2017-11-21 14:43:00,2017-11-28 14:43:00,2017-12-05 14:43:00,2017-12-12 14:43:00,2017-12-19 14:43:00,2017-12-26 14:43:00,2018-01-02 14:43:00,2018-01-09 14:43:00,2018-01-16 14:43:00
1307,2017-01-24 13:05:00,2017-01-31 13:05:00,2017-02-07 13:05:00,2017-02-14 13:05:00,2017-02-21 13:05:00,2017-02-28 13:05:00,2017-03-07 13:05:00,2017-03-14 13:05:00,2017-03-21 13:05:00,2017-03-28 13:05:00,...,2017-11-14 13:05:00,2017-11-21 13:05:00,2017-11-28 13:05:00,2017-12-05 13:05:00,2017-12-12 13:05:00,2017-12-19 13:05:00,2017-12-26 13:05:00,2018-01-02 13:05:00,2018-01-09 13:05:00,2018-01-16 13:05:00
1308,2017-01-24 12:42:00,2017-01-31 12:42:00,2017-02-07 12:42:00,2017-02-14 12:42:00,2017-02-21 12:42:00,2017-02-28 12:42:00,2017-03-07 12:42:00,2017-03-14 12:42:00,2017-03-21 12:42:00,2017-03-28 12:42:00,...,2017-11-14 12:42:00,2017-11-21 12:42:00,2017-11-28 12:42:00,2017-12-05 12:42:00,2017-12-12 12:42:00,2017-12-19 12:42:00,2017-12-26 12:42:00,2018-01-02 12:42:00,2018-01-09 12:42:00,2018-01-16 12:42:00
1309,2017-01-24 11:44:00,2017-01-31 11:44:00,2017-02-07 11:44:00,2017-02-14 11:44:00,2017-02-21 11:44:00,2017-02-28 11:44:00,2017-03-07 11:44:00,2017-03-14 11:44:00,2017-03-21 11:44:00,2017-03-28 11:44:00,...,2017-11-14 11:44:00,2017-11-21 11:44:00,2017-11-28 11:44:00,2017-12-05 11:44:00,2017-12-12 11:44:00,2017-12-19 11:44:00,2017-12-26 11:44:00,2018-01-02 11:44:00,2018-01-09 11:44:00,2018-01-16 11:44:00
1310,2017-01-24 10:53:00,2017-01-31 10:53:00,2017-02-07 10:53:00,2017-02-14 10:53:00,2017-02-21 10:53:00,2017-02-28 10:53:00,2017-03-07 10:53:00,2017-03-14 10:53:00,2017-03-21 10:53:00,2017-03-28 10:53:00,...,2017-11-14 10:53:00,2017-11-21 10:53:00,2017-11-28 10:53:00,2017-12-05 10:53:00,2017-12-12 10:53:00,2017-12-19 10:53:00,2017-12-26 10:53:00,2018-01-02 10:53:00,2018-01-09 10:53:00,2018-01-16 10:53:00
1311,2017-01-24 10:42:00,2017-01-31 10:42:00,2017-02-07 10:42:00,2017-02-14 10:42:00,2017-02-21 10:42:00,2017-02-28 10:42:00,2017-03-07 10:42:00,2017-03-14 10:42:00,2017-03-21 10:42:00,2017-03-28 10:42:00,...,2017-11-14 10:42:00,2017-11-21 10:42:00,2017-11-28 10:42:00,2017-12-05 10:42:00,2017-12-12 10:42:00,2017-12-19 10:42:00,2017-12-26 10:42:00,2018-01-02 10:42:00,2018-01-09 10:42:00,2018-01-16 10:42:00
1312,2017-01-24 09:22:00,2017-01-31 09:22:00,2017-02-07 09:22:00,2017-02-14 09:22:00,2017-02-21 09:22:00,2017-02-28 09:22:00,2017-03-07 09:22:00,2017-03-14 09:22:00,2017-03-21 09:22:00,2017-03-28 09:22:00,...,2017-11-14 09:22:00,2017-11-21 09:22:00,2017-11-28 09:22:00,2017-12-05 09:22:00,2017-12-12 09:22:00,2017-12-19 09:22:00,2017-12-26 09:22:00,2018-01-02 09:22:00,2018-01-09 09:22:00,2018-01-16 09:22:00
1313,2017-01-23 14:12:00,2017-01-30 14:12:00,2017-02-06 14:12:00,2017-02-13 14:12:00,2017-02-20 14:12:00,2017-02-27 14:12:00,2017-03-06 14:12:00,2017-03-13 14:12:00,2017-03-20 14:12:00,2017-03-27 14:12:00,...,2017-11-13 14:12:00,2017-11-20 14:12:00,2017-11-27 14:12:00,2017-12-04 14:12:00,2017-12-11 14:12:00,2017-12-18 14:12:00,2017-12-25 14:12:00,2018-01-01 14:12:00,2018-01-08 14:12:00,2018-01-15 14:12:00
1314,2017-01-23 12:02:00,2017-01-30 12:02:00,2017-02-06 12:02:00,2017-02-13 12:02:00,2017-02-20 12:02:00,2017-02-27 12:02:00,2017-03-06 12:02:00,2017-03-13 12:02:00,2017-03-20 12:02:00,2017-03-27 12:02:00,...,2017-11-13 12:02:00,2017-11-20 12:02:00,2017-11-27 12:02:00,2017-12-04 12:02:00,2017-12-11 12:02:00,2017-12-18 12:02:00,2017-12-25 12:02:00,2018-01-01 12:02:00,2018-01-08 12:02:00,2018-01-15 12:02:00

In [290]:
for column in ideas:
    ideas[column] = ideas[column].dt.week

In [291]:
ideas

,7,14,21,28,35,42,49,56,63,70,...,301,308,315,322,329,336,343,350,357,364
0,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
1,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
2,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
3,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
4,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
5,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
6,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
7,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
8,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
9,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
10,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
11,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
12,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
13,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
14,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
15,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
16,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
17,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
18,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
19,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
20,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
21,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
22,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
23,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
24,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
25,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
26,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
27,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
28,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
29,1,2,3,4,5,6,7,8,9,10,...,43,44,45,46,47,48,49,50,51,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1298,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1299,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1300,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1301,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1302,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1303,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1304,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1305,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1306,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1307,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1308,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1309,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1310,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1311,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1312,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1313,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1314,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1315,4,5,6,7,8,9,10,11,12,13,...,46,47,48,49,50,51,52,1,2,3
1316,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1317,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1318,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1319,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1320,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1321,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1322,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1323,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1324,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1325,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2
1326,3,4,5,6,7,8,9,10,11,12,...,45,46,47,48,49,50,51,52,1,2

### 3. Applying `offsets` 
- Adding each `offset` to `Time` of posting
- Storing as column in `Ideas` DataFrame
- We now have columns representing weekly closing prices for 1 year post-post 
    
    `post-post..get it?`

_Note: That's probably not funny. Just been in the matrix doing my Capstone for 2manyhours_

_Note: Pandas makes this easy!_

### 5. Extracting `Week#`  from datetime objects
_Another cool functionality_
- To further narrow the scope of the data, analysis will be performed on a `weekly` basis
- Pandas to the rescue again! 
- Extracting from all columns:
               Week #
- `Duplicate` date column to prevent losing that data

In [95]:
ideas['Full Date'] = ideas['Time'].copy()   # Duplicating full dates

In [96]:
# Extracting week # 

ideas['Time'] = ideas['Time'].dt.week
ideas['1 Week'] = ideas['1 Week'].dt.week
ideas['2 Week'] = ideas['2 Week'].dt.week
ideas['3 Week'] = ideas['3 Week'].dt.week
ideas['4 Week'] = ideas['4 Week'].dt.week
ideas['5 Week'] = ideas['5 Week'].dt.week
ideas['6 Week'] = ideas['6 Week'].dt.week
ideas['7 Week'] = ideas['7 Week'].dt.week
ideas['8 Week'] = ideas['8 Week'].dt.week
ideas['9 Week'] = ideas['9 Week'].dt.week
ideas['10 Week'] = ideas['10 Week'].dt.week
ideas['11 Week'] = ideas['11 Week'].dt.week
ideas['12 Week'] = ideas['12 Week'].dt.week 
ideas['13 Week'] = ideas['13 Week'].dt.week
ideas['14 Week'] = ideas['14 Week'].dt.week 
ideas['15 Week'] = ideas['15 Week'].dt.week
ideas['16 Week'] = ideas['16 Week'].dt.week
ideas['17 Week'] = ideas['17 Week'].dt.week 
ideas['18 Week'] = ideas['18 Week'].dt.week 
ideas['19 Week'] = ideas['19 Week'].dt.week
ideas['20 Week'] = ideas['20 Week'].dt.week
ideas['21 Week'] = ideas['21 Week'].dt.week
ideas['22 Week'] = ideas['22 Week'].dt.week
ideas['23 Week'] = ideas['23 Week'].dt.week 
ideas['24 Week'] = ideas['24 Week'].dt.week 
ideas['25 Week'] = ideas['25 Week'].dt.week
ideas['26 Week'] = ideas['26 Week'].dt.week
ideas['27 Week'] = ideas['27 Week'].dt.week
ideas['28 Week'] = ideas['28 Week'].dt.week
ideas['29 Week'] = ideas['29 Week'].dt.week
ideas['30 Week'] = ideas['30 Week'].dt.week
ideas['31 Week'] = ideas['31 Week'].dt.week
ideas['32 Week'] = ideas['32 Week'].dt.week
ideas['33 Week'] = ideas['33 Week'].dt.week
ideas['34 Week'] = ideas['34 Week'].dt.week
ideas['35 Week'] = ideas['35 Week'].dt.week 
ideas['36 Week'] = ideas['36 Week'].dt.week 
ideas['37 Week'] = ideas['37 Week'].dt.week 
ideas['38 Week'] = ideas['38 Week'].dt.week
ideas['39 Week'] = ideas['39 Week'].dt.week 
ideas['40 Week'] = ideas['40 Week'].dt.week 
ideas['41 Week'] = ideas['41 Week'].dt.week
ideas['42 Week'] = ideas['42 Week'].dt.week 
ideas['43 Week'] = ideas['43 Week'].dt.week
ideas['44 Week'] = ideas['44 Week'].dt.week
ideas['45 Week'] = ideas['45 Week'].dt.week 
ideas['46 Week'] = ideas['46 Week'].dt.week 
ideas['47 Week'] = ideas['47 Week'].dt.week 
ideas['48 Week'] = ideas['48 Week'].dt.week 
ideas['49 Week'] = ideas['49 Week'].dt.week 
ideas['50 Week'] = ideas['50 Week'].dt.week 
ideas['51 Week'] = ideas['51 Week'].dt.week 
ideas['52 Week'] = ideas['52 Week'].dt.week

## Ready to Merge!

### Plan of Attack:
  - Performing a `leftmerge` to join Stocks onto Ideas, aka:
        Align column names on Stocks DataFrame with column names on Ideas DataFrame
  - This will apply historical stock data for stock ticker each idea is referencing 
  - Opening prices merge will bring in stock prices at the time of article posting
  - Methodology will be repeated for each `offset` aka for 52 weeks/1 year after posting

### What columns to "merge on" ?
  - The Ideas DataFrame is comprised of data that is referencing certain stock tickers, the same stock tickers that created the groundwork for the Stocks DataFrame, so:
        1. Merge on `Tickers`
  - The Stocks DataFrame is comprised of historical timeseries stock data for the range of times used in constructing the webscraper that compiled the Ideas DataFrame. For computational and timing reasons, a weekly analysis was chosen for the scope of this project, so:
        2. Merge on `Week`

### Let's see it done with `OpeningPrices`
#### Notice below how these features are currently being reported in each DataFrame..

In [97]:
ideas.head(1)

,Authors,Link,Tickers,Time,Title,Strategy,1 Week,2 Week,3 Week,4 Week,...,44 Week,45 Week,46 Week,47 Week,48 Week,49 Week,50 Week,51 Week,52 Week,Full Date
0,Bull's Run,/article/4134659-campbell-soup-getting-ready-b...,CPB,52,Campbell Soup Is Getting Ready For A Big Run,Long,1,2,3,4,...,44,45,46,47,48,49,50,51,52,2017-12-31 21:16:00

In [98]:
stocks.head(1)

        Close       Date Tickers  Week
0  116.150002 2017-01-03    AAPL     1

#### Currently:
- Stock tickers being referenced:

        Ideas DataFrame: `Tickers` 
        
        Stocks DataFrame: `Tickers`
        
    _Woot woot! These columns are good to go_

- Our starting point aka opening week aka time of article posting: 
        
        Ideas DataFrame: `Time` column
        
        Stocks DataFrame: `Week` column

#### Change `Week` to `Time`

In [99]:
stocks = stocks.rename(columns={'Week':'Time'}) # Renaming column

- Both columns being merged on are now aligned and _technically_ the dataframes are ready to be merged.
- Let's address arguably the most important feature..
- The historical stock prices:

        Ideas DataFrame: no column for this data- bringing in via merge 
        
        Stocks DataFrame: `Close` column
        
     These values will opening price for our first merge, and will represent weekly closing prices for each subsequent merge on `offset` columns. Opening Price will be compared against offsetted closing prices aka holding periods to evaluate how accurate analyses are when the dust settles 

#### Change `Close` to `OpeningPrice`

In [100]:
stocks = stocks.rename(columns={'Close':'Opening Price'})


#### Merging DataFrames

In [101]:
opening = pd.merge(stocks, ideas, on=['Time','Tickers']) # Merging

opening.head(1)  # Inspecting head

,Opening Price,Date,Tickers,Time,Authors,Link,Title,Strategy,1 Week,2 Week,...,44 Week,45 Week,46 Week,47 Week,48 Week,49 Week,50 Week,51 Week,52 Week,Full Date
0,116.150002,2017-01-03,AAPL,1,Mark Hibben,/article/4034776-apple-oddly-satisfying-touchs...,Apple: The 'Oddly Satisfying' Touchscreen Mac,Long,2,3,...,45,46,47,48,49,50,51,52,1,2017-01-06 10:45:00

- Our opening price has successfully been merged onto the Ideas DataFrame
- Repeat this methodology for all offsets

#### First 10 Weeks...same process

In [102]:
stocks = stocks.rename(columns={'Time':'1 Week','Opening Price':'Week1'}) # Renaming 
week1 = pd.merge(stocks, opening, on=['1 Week','Tickers']) # Merging 
week1.drop_duplicates(subset='Link',inplace=True) # Dropping duplicates

In [103]:
stocks = stocks.rename(columns={'1 Week':'2 Week','Week1':'Week2'}) 
week2 = pd.merge(stocks, week1, on=['2 Week','Tickers'])  
week2.drop_duplicates(subset='Link',inplace=True)

In [104]:
stocks = stocks.rename(columns={'2 Week':'3 Week','Week2':'Week3'}) 
week3 = pd.merge(stocks, week2, on=['3 Week','Tickers']) 
week3.drop_duplicates(subset='Link',inplace=True)

In [105]:
stocks = stocks.rename(columns={'3 Week':'4 Week','Week3':'Week4'})  
week4 = pd.merge(stocks, week3, on=['4 Week','Tickers'])  
week4.drop_duplicates(subset='Link',inplace=True)

In [106]:
stocks = stocks.rename(columns={'4 Week':'5 Week','Week4':'Week5'})  
week5 = pd.merge(stocks, week4, on=['5 Week','Tickers'])  
week5.drop_duplicates(subset='Link',inplace=True)

In [107]:
stocks = stocks.rename(columns={'5 Week':'6 Week','Week5':'Week6'})  
week6 = pd.merge(stocks, week5, on=['6 Week','Tickers'])   
week6.drop_duplicates(subset='Link',inplace=True)

In [108]:
stocks = stocks.rename(columns={'6 Week':'7 Week','Week6':'Week7'})  
week7 = pd.merge(stocks, week6, on=['7 Week','Tickers'])  
week7.drop_duplicates(subset='Link',inplace=True)

In [109]:
stocks = stocks.rename(columns={'7 Week':'8 Week','Week7':'Week8'})  
week8 = pd.merge(stocks, week7, on=['8 Week','Tickers'])  
week8.drop_duplicates(subset='Link',inplace=True)

In [110]:
stocks = stocks.rename(columns={'8 Week':'9 Week','Week8':'Week9'})   
week9 = pd.merge(stocks, week8, on=['9 Week','Tickers'])
week9.drop_duplicates(subset='Link',inplace=True)

In [111]:
stocks = stocks.rename(columns={'9 Week':'10 Week','Week9':'Week10'})  
week10 = pd.merge(stocks, week9, on=['10 Week','Tickers']) 
week10.drop_duplicates(subset='Link',inplace=True)

#### Next 10 Weeks....keep it going

In [112]:
stocks = stocks.rename(columns={'10 Week':'11 Week','Week10':'Week11'})  # Renaming 
week11 = pd.merge(stocks, week10, on=['11 Week','Tickers'])  # Merging 
week11.drop_duplicates(subset='Link',inplace=True)  # Dropping duplicates

In [113]:
stocks = stocks.rename(columns={'11 Week':'12 Week','Week11':'Week12'})
week12 = pd.merge(stocks, week11, on=['12 Week','Tickers'])
week12.drop_duplicates(subset='Link',inplace=True)

In [114]:
stocks = stocks.rename(columns={'12 Week':'13 Week','Week12':'Week13'})
week13 = pd.merge(stocks, week12, on=['13 Week','Tickers'])
week13.drop_duplicates(subset='Link',inplace=True)

In [115]:
stocks = stocks.rename(columns={'13 Week':'14 Week','Week13':'Week14'})
week14 = pd.merge(stocks, week13, on=['14 Week','Tickers'])
week14.drop_duplicates(subset='Link',inplace=True)

In [116]:
stocks = stocks.rename(columns={'14 Week':'15 Week','Week14':'Week15'})
week15 = pd.merge(stocks, week14, on=['15 Week','Tickers'])
week15.drop_duplicates(subset='Link',inplace=True)

In [117]:
stocks = stocks.rename(columns={'15 Week':'16 Week','Week15':'Week16'})
week16 = pd.merge(stocks, week15, on=['16 Week','Tickers'])
week16.drop_duplicates(subset='Link',inplace=True)

In [118]:
stocks = stocks.rename(columns={'16 Week':'17 Week','Week16':'Week17'})
week17 = pd.merge(stocks, week16, on=['17 Week','Tickers'])
week17.drop_duplicates(subset='Link',inplace=True)

In [119]:
stocks = stocks.rename(columns={'17 Week':'18 Week','Week17':'Week18'})
week18 = pd.merge(stocks, week17, on=['18 Week','Tickers'])
week18.drop_duplicates(subset='Link',inplace=True)

In [120]:
stocks = stocks.rename(columns={'18 Week':'19 Week','Week18':'Week19'})
week19 = pd.merge(stocks, week18, on=['19 Week','Tickers'])
week19.drop_duplicates(subset='Link',inplace=True)

In [121]:
stocks = stocks.rename(columns={'19 Week':'20 Week','Week19':'Week20'}) 
week20 = pd.merge(stocks, week19, on=['20 Week','Tickers'])
week20.drop_duplicates(subset='Link',inplace=True)

#### Another 10 Weeks...Sometimes it feels like time goes by this fast huh?

In [122]:
stocks = stocks.rename(columns={'20 Week':'21 Week','Week20':'Week21'})  # Renaming 
week21 = pd.merge(stocks, week20, on=['21 Week','Tickers'])  # Merging
week21.drop_duplicates(subset='Link',inplace=True)

In [123]:
stocks = stocks.rename(columns={'21 Week':'22 Week','Week21':'Week22'})
week22 = pd.merge(stocks, week21, on=['22 Week','Tickers'])
week22.drop_duplicates(subset='Link',inplace=True)

In [124]:
stocks = stocks.rename(columns={'22 Week':'23 Week','Week22':'Week23'})
week23 = pd.merge(stocks, week22, on=['23 Week','Tickers'])
week23.drop_duplicates(subset='Link',inplace=True)

In [125]:
stocks = stocks.rename(columns={'23 Week':'24 Week','Week23':'Week24'})
week24 = pd.merge(stocks, week23, on=['24 Week','Tickers'])
week24.drop_duplicates(subset='Link',inplace=True)

In [126]:
stocks = stocks.rename(columns={'24 Week':'25 Week','Week24':'Week25'})
week25 = pd.merge(stocks, week24, on=['25 Week','Tickers'])
week25.drop_duplicates(subset='Link',inplace=True)

In [127]:
stocks = stocks.rename(columns={'25 Week':'26 Week','Week25':'Week26'})
week26 = pd.merge(stocks, week25, on=['26 Week','Tickers'])
week26.drop_duplicates(subset='Link',inplace=True)

In [128]:
stocks = stocks.rename(columns={'26 Week':'27 Week','Week26':'Week27'})
week27 = pd.merge(stocks, week26, on=['27 Week','Tickers'])
week27.drop_duplicates(subset='Link',inplace=True)

In [129]:
stocks = stocks.rename(columns={'27 Week':'28 Week','Week27':'Week28'})
week28 = pd.merge(stocks, week27, on=['28 Week','Tickers'])
week28.drop_duplicates(subset='Link',inplace=True)

In [130]:
stocks = stocks.rename(columns={'28 Week':'29 Week','Week28':'Week29'})
week29 = pd.merge(stocks, week28, on=['29 Week','Tickers'])
week29.drop_duplicates(subset='Link',inplace=True)

In [131]:
stocks = stocks.rename(columns={'29 Week':'30 Week','Week29':'Week30'})
week30 = pd.merge(stocks, week29, on=['30 Week','Tickers'])
week30.drop_duplicates(subset='Link',inplace=True)

#### 10 More Weeks...Sometimes time drags though

In [132]:
stocks = stocks.rename(columns={'30 Week':'31 Week','Week30':'Week31'})  # Renaming 
week31 = pd.merge(stocks, week30, on=['31 Week','Tickers'])  # Merging 
week31.drop_duplicates(subset='Link',inplace=True)  # Dropping duplicates

In [133]:
stocks = stocks.rename(columns={'31 Week':'32 Week','Week31':'Week32'})
week32 = pd.merge(stocks, week31, on=['32 Week','Tickers'])
week32.drop_duplicates(subset='Link',inplace=True)

In [134]:
stocks = stocks.rename(columns={'32 Week':'33 Week','Week32':'Week33'})
week33 = pd.merge(stocks, week32, on=['33 Week','Tickers'])
week33.drop_duplicates(subset='Link',inplace=True)

In [135]:
stocks = stocks.rename(columns={'33 Week':'34 Week','Week33':'Week34'})
week34 = pd.merge(stocks, week33, on=['34 Week','Tickers'])
week34.drop_duplicates(subset='Link',inplace=True)

In [136]:
stocks = stocks.rename(columns={'34 Week':'35 Week','Week34':'Week35'})
week35 = pd.merge(stocks, week34, on=['35 Week','Tickers'])
week35.drop_duplicates(subset='Link',inplace=True)

In [137]:
stocks = stocks.rename(columns={'35 Week':'36 Week','Week35':'Week36'}) 
week36 = pd.merge(stocks, week35, on=['36 Week','Tickers'])
week36.drop_duplicates(subset='Link',inplace=True)

In [138]:
stocks = stocks.rename(columns={'36 Week':'37 Week','Week36':'Week37'})
week37 = pd.merge(stocks, week36, on=['37 Week','Tickers'])
week37.drop_duplicates(subset='Link',inplace=True)

In [139]:
stocks = stocks.rename(columns={'37 Week':'38 Week','Week37':'Week38'})
week38 = pd.merge(stocks, week37, on=['38 Week','Tickers'])
week38.drop_duplicates(subset='Link',inplace=True)

In [140]:
stocks = stocks.rename(columns={'38 Week':'39 Week','Week38':'Week39'})
week39 = pd.merge(stocks, week38, on=['39 Week','Tickers'])
week39.drop_duplicates(subset='Link',inplace=True)

In [141]:
stocks = stocks.rename(columns={'39 Week':'40 Week','Week39':'Week40'})
week40 = pd.merge(stocks, week39, on=['40 Week','Tickers'])
week40.drop_duplicates(subset='Link',inplace=True)

#### 10 More...with the end near!

In [142]:
stocks = stocks.rename(columns={'40 Week':'41 Week','Week40':'Week41'})  # Renaming 
week41 = pd.merge(stocks, week40, on=['41 Week','Tickers'])  # Merging
week41.drop_duplicates(subset='Link',inplace=True)  # Dropping duplicates

In [143]:
stocks = stocks.rename(columns={'41 Week':'42 Week','Week41':'Week42'})
week42 = pd.merge(stocks, week41, on=['42 Week','Tickers'])
week42.drop_duplicates(subset='Link',inplace=True)

In [144]:
stocks = stocks.rename(columns={'42 Week':'43 Week','Week42':'Week43'})
week43 = pd.merge(stocks, week42, on=['43 Week','Tickers'])
week43.drop_duplicates(subset='Link',inplace=True)

In [145]:
stocks = stocks.rename(columns={'43 Week':'44 Week','Week43':'Week44'})
week44 = pd.merge(stocks, week43, on=['44 Week','Tickers'])
week44.drop_duplicates(subset='Link',inplace=True)

In [146]:
stocks = stocks.rename(columns={'44 Week':'45 Week','Week44':'Week45'})
week45 = pd.merge(stocks, week44, on=['45 Week','Tickers'])
week45.drop_duplicates(subset='Link',inplace=True)

In [147]:
stocks = stocks.rename(columns={'45 Week':'46 Week','Week45':'Week46'})
week46 = pd.merge(stocks, week45, on=['46 Week','Tickers'])
week46.drop_duplicates(subset='Link',inplace=True)

In [148]:
stocks = stocks.rename(columns={'46 Week':'47 Week','Week46':'Week47'})
week47 = pd.merge(stocks, week46, on=['47 Week','Tickers'])
week47.drop_duplicates(subset='Link',inplace=True)

In [149]:
stocks = stocks.rename(columns={'47 Week':'48 Week','Week47':'Week48'})
week48 = pd.merge(stocks, week47, on=['48 Week','Tickers'])
week48.drop_duplicates(subset='Link',inplace=True)

In [150]:
stocks = stocks.rename(columns={'48 Week':'49 Week','Week48':'Week49'})
week49 = pd.merge(stocks, week48, on=['49 Week','Tickers'])
week49.drop_duplicates(subset='Link',inplace=True)

In [151]:
stocks = stocks.rename(columns={'49 Week':'50 Week','Week49':'Week50'})
week50 = pd.merge(stocks, week49, on=['50 Week','Tickers'])
week50.drop_duplicates(subset='Link',inplace=True)

#### ITS THE FINAL COUNTDOWN doodooodooodooodooo...2 more weeks

In [152]:
stocks = stocks.rename(columns={'50 Week':'51 Week','Week50':'Week51'})  # Renaming 
week51 = pd.merge(stocks, week50, on=['51 Week','Tickers'])  # Merging 
week51.drop_duplicates(subset='Link',inplace=True)  # Droppi

In [153]:
stocks = stocks.rename(columns={'51 Week':'52 Week','Week51':'Week52'})
week52 = pd.merge(stocks, week51, on=['52 Week','Tickers'])
week52.drop_duplicates(subset='Link',inplace=True)

In [154]:
# Dropping columns used for merging purposes 

week52.drop(['51 Week','50 Week','49 Week', '48 Week', '47 Week', '46 Week', 
             '45 Week', '44 Week', '43 Week', '42 Week', '41 Week', '40 Week', '39 Week',
             '38 Week', '37 Week', '36 Week', '35 Week', '34 Week', '33 Week', '32 Week',
             '31 Week', '30 Week', '29 Week', '28 Week', '27 Week', '26 Week', '25 Week',
             '24 Week', '23 Week', '22 Week', '21 Week', '20 Week', '19 Week', '18 Week', 
             '17 Week', '16 Week', '15 Week', '14 Week', '13 Week', '12 Week', '11 Week',
             '10 Week','9 Week', '8 Week', '7 Week', '6 Week', '5 Week', '4 Week', '3 Week', 
             '2 Week', '1 Week', '52 Week'],axis=1,inplace=True)

In [155]:
# Reordering columns for readability 

week52 = week52[['Authors','Link','Title','Strategy','Tickers', 'Date','Opening Price','Week1',
        'Week2','Week3','Week4','Week5','Week6','Week7','Week8','Week9','Week10','Week11',
       'Week12','Week13','Week14','Week15','Week16','Week17','Week18', 'Week19','Week20',
       'Week21','Week22','Week23','Week24','Week25','Week26','Week27','Week28','Week29',
       'Week30', 'Week31','Week32','Week33','Week34','Week35','Week36','Week37','Week38',
       'Week39','Week40','Week41','Week42','Week43', 'Week44', 'Week45','Week46','Week47',
       'Week48','Week49','Week50','Week51','Week52']]

---
## Accounting For Actual Performace 
_In order to properly interpret, analyze and model stock recommendations with historical stock pricing timeseries functionality, we must convert datatypes in order to merge the dataframes._

---

In [157]:
# Creating column represening difference in pricing 3 months after opening
week52['Performance'] = week52['Week12'] - week52['Opening Price']

# If increased, apply 0
# If decreased, apply 1
week52['Performance'] = week52['Performance'].apply(
    lambda x: 0 if x > 0.0 else 1)

---
## Saving Results 

---

#### Exporting as CSV  
- Save `Final` `DataFrame` csv file
- Read csv back in to ensure export was successful

In [161]:
# Exporting as csv
week52.to_csv('final_dataframe.csv',index=False)

# Reading csv back in 
week52 = pd.read_csv('final_dataframe.csv')

# Inspecting head
final_dataframe.head(2)

,Authors,Link,Title,Strategy,Tickers,Date,Opening Price,Week1,Week2,Week3,...,Week44,Week45,Week46,Week47,Week48,Week49,Week50,Week51,Week52,Performance
0,Mark Hibben,/article/4034776-apple-oddly-satisfying-touchs...,Apple: The 'Oddly Satisfying' Touchscreen Mac,Long,AAPL,2017-01-03,116.150002,118.989998,120.000000,120.080002,...,174.250000,173.970001,169.979996,174.089996,169.800003,172.669998,176.419998,170.570007,116.150002,0
8,The Entertainment Oracle,/article/4036700-apple-original-programming-ru...,Why The Apple Original Programming Rumors May ...,Long,AAPL,2017-01-09,118.989998,120.000000,120.080002,121.629997,...,173.970001,169.979996,174.089996,169.800003,172.669998,176.419998,170.570007,116.150002,118.989998,0

## Onwards!

---

## Please proceed to Notebook 6 :)